image: node:lts

stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - apps/docs/out/

yarn:install:
  stage: build
  script:
    - npm i turbo -g
    - yarn install --check-files --non-interactive
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

pages:
  stage: deploy
  needs:
    - yarn:install
  script:
    - npm run build
  artifacts:
    paths:
      - apps/docs/out
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH