image: node:lts

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

yarn:install:
  stage: build
  script:
    - npm i turbo -g
    - yarn install --check-files --non-interactive
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_MERGE_REQUEST_ID

pages:
  stage: deploy
  needs:
    - yarn:install
  script:
    - npm run build
    - mkdir public
    - mv apps/docs/out/* public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH